### ISSUE TITLE
[Request] Visual chain

### ISSUE THREAD

**Issue by Psychodeus** [melontini/Linkart#6]
You read it right, visual chain among those minecart.
![pweeese](https://user-images.githubusercontent.com/93028949/194718521-80ea4bbd-067b-49cd-a296-9c5b4b8ff0ea.png)

**Comment by melontini** [comment]
Hey, thanks for your suggestion!

Sadly, I don't think I'm going to maintain linkart for a bit, since I'm not "qualified" enough + I have a few other projects I more enjoy working on + studying.

So I recommend checking out [Cammie's Minecart Tweaks](https://www.curseforge.com/minecraft/mc-mods/cammies-minecart-tweaks) which is like this mod, but better and with a lot more features.

**Comment by Psychodeus** [comment]
Ahh thank you!
